import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
            {
                key: 'apps.source',
                path: '',
                title: 'Source',
                translateKey: 'nav.appsProject.source',
                icon: 'crm',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsProject.find',
                        path: `${APP_PREFIX_PATH}/source/find`,
                        title: 'Find',
                        translateKey: 'nav.appsProject.find',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProject.categories',
                        path: `${APP_PREFIX_PATH}/source/categories`,
                        title: 'Categories',
                        translateKey: 'nav.appsProject.categories',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsProject.recruit',
                        path: `${APP_PREFIX_PATH}/source/recruit`,
                        title: 'Recruit',
                        translateKey: 'nav.appsProject.recruit',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.activate',
                path: '',
                title: 'Activate',
                translateKey: 'nav.appsCrm.activate',
                icon: 'resetPassword',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsCrm.campaign',
                        path: `${APP_PREFIX_PATH}/activate/campaign`,
                        title: 'Campaign',
                        translateKey: 'nav.appsCrm.campaign',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCrm.message',
                        path: `${APP_PREFIX_PATH}/activate/message`,
                        title: 'Message',
                        translateKey: 'nav.appsCrm.message',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsCrm.pay',
                        path: `${APP_PREFIX_PATH}/activate/pay`,
                        title: 'Pay',
                        translateKey: 'nav.appsCrm.pay',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.measure',
                path: '',
                title: 'Measure',
                translateKey: 'nav.appsSales.measure',
                icon: 'measure',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsSales.reporting',
                        path: `${APP_PREFIX_PATH}/measure/reporting`,
                        title: 'Reporting',
                        translateKey: 'nav.appsSales.reporting',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsSales.content',
                        path: `${APP_PREFIX_PATH}/measure/content`,
                        title: 'Content',
                        translateKey: 'nav.appsSales.content',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsSales.integrations',
                path: `${APP_PREFIX_PATH}/integrations`,
                title: 'Integrations',
                translateKey: 'nav.appsSales.integrations',
                icon: 'integrate',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'appsSales.settings',
                path: `${APP_PREFIX_PATH}/settings`,
                title: 'Settings',
                translateKey: 'nav.appsSales.settings',
                icon: 'setting',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
]


export default appsNavigationConfig
